bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Frog Suit",
    "Pajamas",
    "All Suits (Minus Tao and Super Chibi Robo)",
    "All Tools",
    "Obtain Spoon",
    "Obtain Squirter",
    "Obtain Radar",
    "Utilibots Sticker",
    "Deliver the Red Shoe",
    "All Doors Living Room",
    "All Doors Foyer",
    "All Doors Backyard",
    "All Doors Jenny’s Room",
    "All Doors Basement",
    "Gunpowder",
    "Bandage Delivery",
    "Ticket Stub Delivery",
    "Fill Crayon Box",
    "3 Frog Rings",
    "6 Frog Rings",
    "9 Frog Rings",
    "The Past",
    "Charge Giga Battery",
    "Divorce",
    "Peekoe Sticker",
    "Deliver First Sophie Letter",
    "Mr Prongs Sticker",
    "Engagement Ring",
    "Deliver Pirate Ship",
    "Assemble Full Pirate Crew",
    "Assemble 2 Pirate Crew Members",
    "700 Happy Points",
    "1500 Happy Points",
    "3000 Happy Points",
    "5000 Happy Points",
    "1500 Scrap",
    "2500 Scrap",
    "3500 Scrap",
    "4000 Moolah",
    "8000 Moolah",
    "14000 Moolah",
    "20000 Moolah",
    "Frog Sticker",
    "Cooking Sticker",
    "Alien Ear Chip",
    "Range Chip",
    "All Chips/Upgrades",
    "White Brick",
    "Red Brick",
    "Green Brick",
    "Rail Training",
    "Spy Training",
    "Blue Flower to Mom",
    "Pink Flower to Mom",
    "White flower to Mom",
    "Dog Bone",
    "Patrol with Drake Redcrest",
    "Deliver Dog Tags"
];
